# Generated by Django 6.0 on 2025-12-26 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name='學號')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('department_code', models.CharField(blank=True, default='', max_length=20, verbose_name='系所代碼')),
                ('grade', models.CharField(blank=True, default='', max_length=10, verbose_name='年級')),
                ('class_group', models.CharField(blank=True, default='', max_length=20, verbose_name='班組')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ch', models.CharField(max_length=50, verbose_name='中文姓名')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='英文姓名')),
                ('extension', models.CharField(blank=True, default='', max_length=20, verbose_name='校內分機')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='E-mail')),
                ('office', models.CharField(blank=True, default='', max_length=100, verbose_name='辦公室/地點')),
                ('intro', models.TextField(blank=True, default='', verbose_name='老師簡介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, default='', max_length=10)),
                ('semester', models.CharField(max_length=10)),
                ('teacher', models.CharField(blank=True, default='', max_length=50)),
                ('course_code', models.CharField(blank=True, default='', max_length=50)),
                ('department_code', models.CharField(blank=True, default='', max_length=20)),
                ('core_code', models.CharField(blank=True, default='', max_length=20)),
                ('group_code', models.CharField(blank=True, default='', max_length=20)),
                ('grade', models.CharField(blank=True, default='', max_length=10)),
                ('class_group', models.CharField(blank=True, default='', max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('division', models.CharField(blank=True, default='', max_length=20)),
                ('system', models.CharField(blank=True, default='', max_length=30)),
                ('teaching_group', models.CharField(blank=True, default='', max_length=50)),
                ('week_info', models.CharField(blank=True, default='', max_length=50)),
                ('day', models.CharField(blank=True, default='', max_length=5)),
                ('period', models.CharField(blank=True, default='', max_length=20)),
                ('classroom', models.CharField(blank=True, default='', max_length=100)),
                ('course_summary_ch', models.TextField(blank=True, null=True)),
                ('course_summary_en', models.TextField(blank=True, null=True)),
                ('teacher_old_code', models.CharField(blank=True, default='', max_length=20)),
                ('course_old_code', models.CharField(blank=True, default='', max_length=20)),
                ('schedule_old_code', models.CharField(blank=True, default='', max_length=20)),
                ('schedule_old_name', models.CharField(blank=True, default='', max_length=50)),
                ('teacher_old_code2', models.CharField(blank=True, default='', max_length=20)),
                ('teacher_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='main.teacher', verbose_name='老師(關聯)')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='main.student')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
